import { useTranslation } from 'react-i18next';
import LegalLayout from '../../layouts/LegalLayout';

export default function AiDisclaimer() {
  const { i18n } = useTranslation();
  const isVi = i18n.language === 'vi' || i18n.language?.startsWith('vi');

  if (isVi) {
    return (
      <LegalLayout title="Tuyên bố Miễn trừ Trách nhiệm AI" lastUpdated="15 tháng 6, 2026">
        <p className="lead text-lg text-slate-600 dark:text-slate-300">
          BanknoteAI sử dụng hệ thống Trí tuệ Nhân tạo đa tác tử tự cấu hình để phân loại, phân tích và xem xét các tờ tiền được tải lên. Vui lòng đọc kỹ tuyên bố miễn trừ này để hiểu rõ về khả năng cũng như giới hạn của hệ thống.
        </p>

        <h2>1. Bản chất của Dịch vụ</h2>
        <p>
          Hệ thống nhận diện của chúng tôi điều phối nhiều tác tử độc lập (bao gồm mô hình học sâu phân loại ảnh, mô hình ngôn ngữ lớn LLM để đọc chữ/số seri và tác tử đối sánh thị giác). Hệ thống sẽ tổng hợp phiếu bầu của từng tác tử và chạy thuật toán biểu quyết đồng thuận để ước lượng mệnh giá, quốc gia, năm phát hành và chất liệu của tờ tiền giấy.
        </p>

        <h2>2. Không thay thế Giám định pháp lý</h2>
        <p>
          <strong>BanknoteAI KHÔNG phải là một tổ chức tài chính, ngân hàng trung ương hay cơ quan giám định tiền tệ được pháp luật cấp phép.</strong> Các kết quả phân tích chỉ chỉ ra xác suất trùng khớp về mặt hình học và dữ liệu văn bản của tờ tiền. Hệ thống của chúng tôi không thể phát hiện các loại tiền giả tinh vi (ví dụ: tiền giả có mực từ tính, độ sâu của kỹ thuật in chìm intaglio, hay các sợi bảo an siêu vi) vốn đòi hỏi các thiết bị phân tích vật lý chuyên dụng.
        </p>

        <h2>3. Giới hạn kỹ thuật của Học máy & LLM</h2>
        <p>
          Hệ thống AI chịu tác động từ các yếu tố kỹ thuật khách quan sau:
        </p>
        <ul>
          <li><strong>Chất lượng hình ảnh:</strong> Ảnh chụp bị mờ, thiếu sáng, góc chụp quá nghiêng, hoặc tờ tiền bị nhàu nát, rách nặng sẽ làm giảm độ chính xác của phân tích.</li>
          <li><strong>Sự ảo tưởng (Hallucination):</strong> Các tác tử LLM đôi khi có thể đưa ra mô tả lịch sử hoặc chi tiết bảo an không chính xác dựa trên suy luận ngữ cảnh.</li>
          <li><strong>Dữ liệu ngoài phạm vi:</strong> Các tờ tiền quá cổ, tiền cổ vật hoặc tiền kỷ niệm phiên bản giới hạn có thể không nằm trong tập dữ liệu huấn luyện của mô hình.</li>
        </ul>

        <h2>4. Trách nhiệm của Người dùng</h2>
        <p>
          Khi sử dụng dịch vụ này, bạn thừa nhận và đồng ý rằng:
        </p>
        <ul>
          <li>Bạn sẽ không sử dụng BanknoteAI làm công cụ ra quyết định duy nhất cho các giao dịch tài chính hoặc trao đổi tiền mặt có giá trị lớn.</li>
          <li>Bạn sẽ tự đối chiếu thủ công các chi tiết quan trọng (như mã tiền tệ, trạng thái lưu hành) trước khi thực hiện quy đổi tiền tệ thực tế.</li>
          <li>Bạn tự chịu mọi rủi ro tài chính phát sinh từ việc tin dùng kết quả của hệ thống.</li>
        </ul>
      </LegalLayout>
    );
  }

  // Fallback to English
  return (
    <LegalLayout title="AI Disclaimer" lastUpdated="June 15, 2026">
      <p className="lead text-lg text-slate-600 dark:text-slate-300">
        BanknoteAI utilizes a custom Multi-Agent Artificial Intelligence system to classify, parse, and review banknote uploads. Please read this AI Disclaimer carefully to understand the capabilities and limitations of our system.
      </p>

      <h2>1. Nature of the Service</h2>
      <p>
        Our recognition engine leverages multiple independent AI sub-systems (including deep learning classification models, Large Language Models (LLMs) via APIs, and visual search lookup pipelines) to analyze images of paper and polymer banknotes. The platform aggregates individual agent inferences and uses a consensus voting algorithm to determine the most likely denomination, country of origin, series year, and material.
      </p>

      <h2>2. No Authentication Guarantees</h2>
      <p>
        <strong>BanknoteAI is NOT a banking institution, treasury, or authorized currency authenticator.</strong> The results generated by our agents indicate a high-probability match of visual features, but they do NOT constitute legal proof of currency authenticity. Our system cannot detect sophisticated physical counterfeits (e.g., matching magnetic ink signatures, tactile intaglio printing depth, or microscopic threads) that require mechanical bank sorting equipment or forensic validation.
      </p>

      <h2>3. Limitations of Machine Learning & LLMs</h2>
      <p>
        AI systems are subject to specific technical limitations, including but not limited to:
      </p>
      <ul>
        <li><strong>Image Quality Dependencies:</strong> Low resolution, poor lighting, extreme angles, severe wrinkles, or tears in the banknote image can significantly degrade agent classification scores.</li>
        <li><strong>Hallucinations:</strong> The Large Language Model agents may occasionally "hallucinate" historical information, security features, or translations of foreign script printed on a banknote that are not present.</li>
        <li><strong>Out-of-Distribution Data:</strong> Extremely rare, ancient, or heavily customized commemorative banknotes may not be accurately categorized if they fall outside the training distributions of our models.</li>
      </ul>

      <h2>4. User Responsibility and Safeguards</h2>
      <p>
        By using this service, you acknowledge and agree that:
      </p>
      <ul>
        <li>You will not use BanknoteAI as the sole decision-maker for financial transactions involving physical cash exchanges.</li>
        <li>You will independently verify critical details, such as the currency code, active circulation status, and exchange rates prior to conducting currency trades.</li>
        <li>You assume all risks associated with any actions or financial losses taken in reliance on the outputs of the consensus engine.</li>
      </ul>

      <h2>5. Feedback and Model Fine-Tuning</h2>
      <p>
        We are continuously training our ML models and system agents to improve recognition accuracy. If you notice a scan that returned an incorrect consensus or failed to identify a common regional banknote, please use the "Feedback" button on the scan result page to alert our administrators. Your flagged issues help us optimize agent configurations.
      </p>
    </LegalLayout>
  );
}

